variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build-container:
  stage: build
  script:
    ## Login to Gitlab Provided Container Registry for this project.
    - cd frontend
    - git checkout master
    - git pull 
    - cd .. 
    - docker info
    - docker-compose build --pull
  only:
    - master

deploy-target:
  stage: deploy
  script:
    - docker-compose ps | grep 'Up' && docker-compose down
    - docker-compose up -d  
  only:
    - master
