spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            token-uri: https://login.microsoftonline.com/33d8cf3c-2f14-48c0-9ad6-5d2825533673/oauth2/v2.0/token
            authorization-uri:  https://login.microsoftonline.com/33d8cf3c-2f14-48c0-9ad6-5d2825533673/oauth2/v2.0/authorize
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwks-uri: https://login.microsoftonline.com/33d8cf3c-2f14-48c0-9ad6-5d2825533673/discovery/v2.0/keys
            user-name-attribute: name
        registration:
          azure:
            client-authentication-method: BASIC
            provider: azure
            client-id: 0c080e9a-d3cd-4047-8287-42b13b386f97
            client-secret: mhWqi@Kdkv51[lO88c=btuu-.ctMPc=i
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            scope:
              - https://graph.microsoft.com/openid
              - https://graph.microsoft.com/profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 7200000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8100/tab1/oauth2/redirect
      - http://localhost:8100/tab1

azure:
  activedirectory:
    tenant-id: 33d8cf3c-2f14-48c0-9ad6-5d2825533673
    active-directory-groups:
      - Users
